### ISSUE TITLE
FEATURE REQUEST: [SLM] Add a second time under “Scheduler” setting

### ISSUE THREAD

**Issue by cyberskier** [babsonnexus/stream-link-manager-for-channels#10]
I just checked the times that most streaming services drop new episodes, and most of them release new episodes at midnight Pacific, or early in the a.m. Pacific time, but Amazon usually releases new episodes at midnight GMT, which is in the evening Pacific time. That means there could be a lag of several hours for new episodes to make their way into Channels if the Scheduler is set to target one or the other of these times.

If it isn’t taxing on the server, a nice touch would be to be able to specific two times that SLM checks for new episodes. 

(I’m not familiar enough with GitHub to know how to tag this request “Enhancement”, or maybe users can’t do that)

**Comment by babsonnexus** [comment]
I get what you're saying, but I'm quite concerned about doing something as intensive as the end-to-end process against JustWatch too often; I really don't want to set off any red flags for them. Also, speaking of JustWatch, even if the streaming service releases at a certain time, it doesn't mean JustWatch adds it at that time. I'm not exactly sure what their schedule is, but I've run the "New & Updated" search several times during the same day and the content changed during that timeframe. As such, I think I'd rather leave things as-is for the time being.

**Comment by babsonnexus** [comment]
I will add a dropdown for frequency with every 24, 12, and 8 hours as options.

**Comment by cyberskier** [comment]
Great, thank you!!

**Comment by babsonnexus** [comment]
This will be available in the next release:

![image](https://github.com/user-attachments/assets/f00ea8aa-cc31-47bc-9b5a-a8f598addf20)

![image](https://github.com/user-attachments/assets/7b86e9c8-66c9-42f6-bc6f-a702ca8ceae4)

**Comment by babsonnexus** [comment]
This is available as of v2024.11.05.1648
