### ISSUE TITLE
Changing a playlist IP after the fact doesnt update the m3u

### ISSUE THREAD

**Issue by SethL** [babsonnexus/stream-link-manager-for-channels#18]
Had a situation where I changed the ip of a playlist and the change was not reflected on the m3u output. I had to delete the app dir and restart the container and start over.

**Comment by babsonnexus** [comment]
It's not instant; you have to run `Update Station List` to get changes from your source Playlists:

![image](https://github.com/user-attachments/assets/4d81df0e-64ff-4d24-a134-1b709541115f)

Or let it run naturally:

![image](https://github.com/user-attachments/assets/f177e644-7dc9-4cfe-8eb2-86b1f32a79ac)

Once those are updated, then you can run the process for the m3u/EPG output (or, again, let it run naturally). Without both of these steps run, your m3u/EPG output will remain as it was before.

**Comment by SethL** [comment]
I was sure I did that but I will try again
