### ISSUE TITLE
XML issues

### ISSUE THREAD

**Issue by SethL** [babsonnexus/stream-link-manager-for-channels#21]
Also posted in the forum but wanted to follow proper protocol and open an issue on github as well.

My issue now is for my xml guide sources, slm will not create an xml file no matter what I do.

I added my source
![image](https://github.com/user-attachments/assets/8ce33aeb-683e-42fe-a116-5c39cab68c62)

The epg is from channels, it opens fine in the browser
![image](https://github.com/user-attachments/assets/d938e8fe-08b8-466b-a882-b34613d1e199)

However it never generates a xmlepg for mpeg-ts
![image](https://github.com/user-attachments/assets/512a77aa-638d-4c58-bd78-8416b3985816)

Looking at the logs it appears that is downloading it (192.168.12.33 is my other Channels server and 192.168.12.8 is my frndly container) When i added the frndly epg xml it worked great, I added the channels as parent stations and then the xml link appeared. Not so much luck with the other Channels source. I have tried using:
```
http://192.168.12.33:8089/devices/M3U-AUFreeview/guide/xmltv?duration=1209600 (Channels Server)
https://i.mjh.nz/nz/epg.xml (Guide xml as configured on the Channels Server)
https://raw.githubusercontent.com/matthuisman/i.mjh.nz/e2c6e58798b3583db18513ea088478da01fd5e08/nz/epg.xml (cname it resolves to)
```
None of them work and slm just ignores them.
Any insight you could provide would be very helpful 
Thanks!
```
[DEBUG | 2024-11-04 16:38:06,186] - Starting new HTTP connection (1): 192.168.12.33:8089
[DEBUG | 2024-11-04 16:38:06,197] - http://192.168.12.33:8089 "GET /devices/M3U-AUFreeview/guide/xmltv HTTP/11" 200 None
[DEBUG | 2024-11-04 16:38:06,214] - Encoding detection: utf_8 is most likely the one.
[DEBUG | 2024-11-04 16:38:06,215] - Starting new HTTP connection (1): 192.168.12.8:80
[DEBUG | 2024-11-04 16:38:06,329] - http://192.168.12.8:80 "GET /epg.xml?gracenote=exclude HTTP/10" 200 None
[DEBUG | 2024-11-04 16:38:06,684] - Encoding detection: utf_8 is most likely the one.
[DEBUG | 2024-11-04 16:38:06,685] - Starting new HTTPS connection (1): raw.githubusercontent.com:443
[DEBUG | 2024-11-04 16:38:06,710] - https://raw.githubusercontent.com:443 "GET /matthuisman/i.mjh.nz/e2c6e58798b3583db18513ea088478da01fd5e08/nz/epg.xml HTTP/11" 200 1130329

```

**Comment by babsonnexus** [comment]
This is covered here:

https://community.getchannels.com/t/beta-playlist-manager-for-channels-slm-add-on/41719/38
